### ISSUE TITLE
Readme on thinking-sphinx-3 recipe is *wrong*

### ISSUE THREAD

**Issue by jamez01** [engineyard/ey-cloud-recipes#130]
Hey,

Readme on thinking-sphinx-3 recipe says `include_recipe "sphinx"` but should read `include_recipe "thinking-sphinx-3"`

Thanks :two_men_holding_hands:

- James

**Comment by dvalfre** [comment]
Reckon this is fixed, as per what https://github.com/engineyard/ey-cloud-recipes/tree/master/cookbooks/thinking-sphinx-3.  Feel free to close the issue if deemed so.  Thanks!
