### ISSUE TITLE
Elasticsearch recipes includes a ~3 year old version

### ISSUE THREAD

**Issue by kaspergrubbe** [engineyard/ey-cloud-recipes#181]
`Elasticsearch 0.18.2` was released October 27, 2011. That is 2 years 11 months 26 days ago. 

A new revision of these recipes could be nice.

**Comment by dvalfre** [comment]
We have updated the relevant cookbooks as per https://support.cloud.engineyard.com/entries/91300537-Elasticsearch-vulnerabilities-
Please test it and feel free to mark close the issue if deemed so.

**Comment by kaspergrubbe** [comment]
Hi,

Thanks for getting back to me, we upgraded to a higher version internally, so I can't verify if your updated cookbooks works, but it is nice to see an upgrade :+1:
