### ISSUE TITLE
Updated DelayedJob recipe to have default values for newer instance types

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cloud-recipes#230]
https://github.com/engineyard/ey-cloud-recipes/blob/master/cookbooks/delayed_job/recipes/default.rb#L10-L20

Get the default worker counts from https://support.cloud.engineyard.com/hc/en-us/articles/205407758-Worker-Allocation-on-Engine-Yard-Cloud

**Comment by dvalfre** [comment]
It also has to take into account if the env has more than one app, i.e.:  if an c1.xlarge can handle 8 workers, should those be evenly shared among `node[:applications].each` ?

**Comment by mikong** [comment]
@radamanthus, I'll work on this after #319 gets merged.
