### ISSUE TITLE
Sunspot recipe

### ISSUE THREAD

**Issue by radamanthus** [engineyard/ey-cloud-recipes#287]
The sunspot gem is still alive and kicking. Please do not deprecate the recipe. 

The latest version of the gem integrates Solr 5.3 and it is possible to run Solr from it while keeping SOLR_HOME in `/data/solr`. Here are the manual steps to setup Sunspot:

1\. Copy `/data/appname/current/solr` to `/data/solr`

2\. Add the line

```
solr_home: /data/solr
```

to `/data/appname/current/solr.yml

3\. Start solr with `bundle exec rake sunspot:solr:start`

Please update the Sunspot recipe with the above steps in mind.

**Comment by radamanthus** [comment]
https://github.com/engineyard/ey-cloud-recipes/pull/290

**Comment by dvalfre** [comment]
@radamanthus are we ok to close this one?
